package com.floatinity.toolIt.exceptions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.floatinity.toolIt.util.LocalizationController;

public enum ToolItError {

	TI_APPLICATION_ERROR(1001, "TI_APPLICATION_ERROR"), //
	TI_DB_ERROR(1002, "TI_DB_ERROR"), //
	TI_ERR_HTTP_SERVER_ERROR(1003, "TI_ERR_HTTP_SERVER_ERROR"), //
	TI_ERR_INVALID_PAYLOAD(1004, "TI_ERR_INVALID_PAYLOAD"), //
	TI_ERR_INVALID_HTTP_METHOD(1005, "TI_ERR_INVALID_HTTP_METHOD"), //
	TI_ERR_INVALID_RESPONSE(1006, "TI_ERR_INVALID_RESPONSE"), //
	TI_ERR_VALIDATION_FAILED(1007, "TI_ERR_VALIDATION_FAILED"), //
	TI_ERR_PERMISSION_DENIED(1008, "TI_ERR_PERMISSION_DENIED"), //
	TI_ERR_TOKEN_AUTH_FAILURE(1009, "TI_ERR_TOKEN_AUTH_FAILURE"), //
	TI_ERR_INVALID_SESSION(1010, "TI_ERR_INVALID_SESSION"), //
	TI_ERR_USERNAME_INVALID(1011, "TI_ERR_USERNAME_INVALID"), //
	TI_ERR_PASSWORD_INVALID(1012, "TI_ERR_PASSWORD_INVALID"), //
	TI_ERR_USER_DOES_NOT_EXIST(1013, "TI_ERR_USER_DOES_NOT_EXIST"), //
	TI_ERR_USER_DOES_NOT_HAVE_LOGIN_ACCESS(1014, "TI_ERR_USER_DOES_NOT_HAVE_LOGIN_ACCESS"), //
	TI_ERR_IMPORT_BASE_PATH_NOT_FOUND(1015, "TI_ERR_IMPORT_BASE_PATH_NOT_FOUND"), //
	TI_ERR_REQUEST_INFO_NOT_FOUND(1016, "TI_ERR_REQUEST_INFO_NOT_FOUND"),
	TI_ERR_IN_STORING_FILE(1017, "TI_ERR_IN_STORING_FILE"), TI_ERR_IN_DELETING_FILE(1018, "TI_ERR_IN_DELETING_FILE"),
	TI_ERR_INVALID_PHONE_NUMBER(1019, "TI_ERR_INVALID_PHONE_NUMBER"),
	TI_ERR_INVALID_MOBILE_NUMBER(1020, "TI_ERR_INVALID_MOBILE_NUMBER"),
	TI_ERR_BATCH_REQUEST_ELEMENT_IDENTIFIER_INVALID(1021, "TI_ERR_BATCH_REQUEST_ELEMENT_IDENTIFIER_INVALID"), //
	TI_ERR_INVALID_MAC_ADDRESS(1022, "TI_ERR_INVALID_MAC_ADDRESS"),

	// API Errors
	// Operator API Errors
	TI_ERR_INVALID_OPERATOR_ID(2001, "TI_ERR_INVALID_OPERATOR_ID"),
	TI_ERR_INVALID_OPERATOR_FNAME(2002, "TI_ERR_INVALID_OPERATOR_FNAME"),
	TI_ERR_INVALID_OPERATOR_MNAME(2003, "TI_ERR_INVALID_OPERATOR_MNAME"),
	TI_ERR_INVALID_OPERATOR_LNAME(2004, "TI_ERR_INVALID_OPERATOR_LNAME"),
	TI_ERR_INVALID_OPERATOR_TICKETNO(2006, "TI_ERR_INVALID_OPERATOR_TICKETNO"),
	TI_ERR_INVALID_OPERATOR_RFID(2005, "TI_ERR_INVALID_OPERATOR_RFID"),
	TI_ERR_INVALID_OPERATOR_HAND(2007, "TI_ERR_INVALID_OPERATOR_HAND"),
	TI_ERR_INVALID_OPERATOR_FINGER(2008, "TI_ERR_INVALID_OPERATOR_FINGER"),
	TI_ERR_INVALID_OPERATOR_FINGERPRINT(2009, "TI_ERR_INVALID_OPERATOR_FINGERPRINT"),

	// Operator API Errors
	TI_ERR_INVALID_DEPT_ID(2551, "TI_ERR_INVALID_DEPT_ID"), TI_ERR_INVALID_DEPT_NAME(2552, "TI_ERR_INVALID_DEPT_NAME"),

	// Line API Errors
	TI_ERR_INVALID_LINE_ID(3001, "TI_ERR_INVALID_LINE_ID"), TI_ERR_INVALID_LINE_NO(3002, "TI_ERR_INVALID_LINE_NO"),
	TI_ERR_INVALID_LINE_NAME(3003, "TI_ERR_INVALID_LINE_NAME"),

	// Die API Errors
	TI_ERR_INVALID_DIE_ID(3551, "TI_ERR_INVALID_DIE_ID"), TI_ERR_INVALID_DIE_NUMBER(3552, "TI_ERR_INVALID_DIE_NUMBER"),
	TI_ERR_INVALID_DIE_CUSTOMER(3552, "TI_ERR_INVALID_DIE_CUSTOMER"),

	// Machine API Errors
	TI_ERR_INVALID_MACHINE_ID(4001, "TI_ERR_INVALID_MACHINE_ID"),
	TI_ERR_INVALID_MACHINE_NO(4002, "TI_ERR_INVALID_MACHINE_NO"),
	TI_ERR_INVALID_MACHINE_NAME(4003, "TI_ERR_INVALID_MACHINE_NAME"),
	TI_ERR_INVALID_MACHINE_RFID(4004, "TI_ERR_INVALID_MACHINE_RFID"),

	// Operation API Errors
	TI_ERR_INVALID_OPERATION_ID(4551, "TI_ERR_INVALID_OPERATION_ID"),
	TI_ERR_INVALID_OPERATION_NAME(4552, "TI_ERR_INVALID_OPERATION_NAME"),

	// Tool API Error
	TI_ERR_INVALID_TOOL_ID(5001, "TI_ERR_INVALID_TOOL_ID"),
	TI_ERR_INVALID_TOOL_SHOP_CODE(5002, "TI_ERR_INVALID_TOOL_SHOP_CODE"),
	TI_ERR_INVALID_TOOL_SAP_CODE(5003, "TI_ERR_INVALID_TOOL_SAP_CODE"),
	TI_ERR_INVALID_TOOL_COST(5004, "TI_ERR_INVALID_TOOL_COST"), TI_INVALID_DRAW_VALUE(5005, "TI_INVALID_DRAW_VALUE"),
	TI_ERR_GET_TOOL_CHUNK_FAILED(5006, "TI_ERR_GET_TOOL_CHUNK_FAILED"),

	// ToolAssignment API Error
	TI_ERR_NO_MACHINE_FOUND_FOR_TAG(5551, "TI_ERR_NO_MACHINE_FOUND_FOR_TAG"),
	TI_ERR_NO_Die_IS_ASSIGNED_TO_LINE(5552, "TI_ERR_NO_Die_IS_ASSIGNED_TO_LINE"),
	TI_ERR_OPERATOR_LINE_MACHINE_LINE_DIFFERENT(5553, "TI_ERR_OPERATOR_LINE_MACHINE_LINE_DIFFERENT"),
	TI_ERR_INVALID_OPERATORS_LINE(5554, "TI_ERR_INVALID_OPERATORS_LINE"),
	TI_ERR_NO_TOOL_ASSIGNED(5555, "TI_ERR_NO_TOOL_ASSIGNED"),
	TI_ERR_NO_OPERATION_ASSIGNED(5556, "TI_ERR_NO_OPERATION_ASSIGNED"),
	TI_ERR_UNABLE_TO_ASSIGN_TOOLS(5557, "TI_ERR_UNABLE_TO_ASSIGN_TOOLS"),
	TI_ERR_INVALID_QTY(5558, "TI_ERR_INVALID_QTY"), TI_ERR_INVALID_TOOL_IDS(5559, "TI_ERR_INVALID_TOOL_IDS"),
	TI_ERR_INVALID_SAP_CODE_IN_SAPDATA(6000, "TI_ERR_INVALID_SAP_CODE_IN_SAPDATA"),

	// ReportRequest API Error
	TI_ERR_INVALID_START_DATE(6001, "TI_ERR_INVALID_START_DATE"),
	TI_ERR_INVALID_END_DATE(6002, "TI_ERR_INVALID_END_DATE"),
	TI_ERR_INVALID_REPORT_TYPE(6003, "TI_ERR_INVALID_REPORT_TYPE"),

	// Notification API Error
	TI_ERR_INVALID_NOTIFICATION_ID(6551, "TI_ERR_INVALID_NOTIFICATION_ID"),
	TI_ERR_INVALID_USER_ID(6552, "TI_ERR_INVALID_USER_ID"),
	TI_ERR_INVALID_NOTIFICATION_ACTION(6553, "TI_ERR_INVALID_NOTIFICATION_ACTION"),

	// Export API Error
	TI_ERR_UNABLE_TO_READ_EXPORT_TEMPALTE(7001, "TI_ERR_UNABLE_TO_READ_EXPORT_TEMPALTE"),
	TI_ERR_UNABLE_TO_WRITE_CSV(7002, "TI_ERR_UNABLE_TO_WRITE_CSV"),
	TI_ERR_DOWNLOAD_FAILED(7003, "TI_ERR_DOWNLOAD_FAILED"), TI_ERR_INVALID_IDS(7004, "TI_ERR_INVALID_IDS"),
	TI_ERR_INVALID_EXPORTTYPE(7005, "TI_ERR_INVALID_EXPORTTYPE"),

	// OperationGroup API Error
	TI_ERR_INVALID_OPERATION_GROUP_ID(7551, "TI_ERR_INVALID_OPERATION_GROUP_ID"),
	TI_ERR_INVALID_OPERATION_GROUP_NAME(7552, "TI_ERR_INVALID_OPERATION_GROUP_NAME"),

	// ProjetPlan API error
	TI_ERR_INVALID_PROJECTPLAN_ID(8001, "TI_ERR_INVALID_PROJECTPLAN_ID"),
	TI_ERR_PROJECT_PLAN_EXIST_FOR_THIS_LINE_AND_DIE(8002, "TI_ERR_PROJECT_PLAN_EXIST_FOR_THIS_LINE_AND_DIE"),
	TI_ERR_INVALID_PROJECT_STATUS(8003, "TI_ERR_INVALID_PROJECT_STATUS"),
	TI_ERR_PROJECT_PLAN_EXIST_FOR_THIS_LINE(8004, "TI_ERR_PROJECT_PLAN_EXIST_FOR_THIS_LINE"),
	TI_ERR_UNABLE_TO_UPDATE_PROJECT_PLAN(8005, "TI_ERR_UNABLE_TO_UPDATE_PROJECT_PLAN"),
	TI_ERR_UNABLE_TO_DELETE_PROJECT_PLAN(8006, "TI_ERR_UNABLE_TO_DELETE_PROJECT_PLAN"),
	TI_ERR_PROJECT_PLAN_ALREADY_SCHEDULED_FOR_THIS_LINE_AND_TIME(8007,
			"TI_ERR_PROJECT_PLAN_ALREADY_SCHEDULED_FOR_THIS_LINE_AND_TIME"),

	// BatchJobDetail
	TI_ERR_INVALID_JOB_ID(8551, "TI_ERR_INVALID_JOB_ID"), TI_ERR_INVALID_JOB(8552, "TI_ERR_INVALID_JOB"),//
	TI_ERR_INVALID_TOKEN(8552,"TI_ERR_INVALID_TOKEN"),//
	TI_ERR_DECRYPTION_FAILED(8553,"TI_ERR_DECRYPTION_FAILED"),// 
	TI_ERR_NEW_PASSWORD_INVALID(8554,"	TI_ERR_NEW_PASSWORD_INVALID"),//
	TI_ERR_INVALID_PASSWORD_COMBINATION(8556,"TI_ERR_INVALID_PASSWORD_COMBINATION"),//
	TI_ERR_USER_NOT_ACTIVE(8557,"TI_ERR_USER_NOT_ACTIVE"),//
	TI_ERR_DEMO_LICENSE_EXPIRED(8558,"TI_ERR_DEMO_LICENSE_EXPIRED"),

	;

	;
	private int errCode;

	private String errKey;

	private String errMsg;

	ToolItError(int errorCode, String errorKey) {
		this.errCode = errorCode;
		this.errKey = errorKey;
//		this.errMsg = LocalizationController.getMessage(errorKey);
	}

	@JsonCreator
	public static ToolItError forValue(String value) {
		for (ToolItError error : values()) {
			if (error.getErrKey().equalsIgnoreCase(value)) {
				return error;
			}
		}
		return null;
	}

	public int getErrCode() {
		return errCode;
	}

	public void setErrCode(int errCode) {
		this.errCode = errCode;
	}

	public String getErrKey() {
		return errKey;
	}

	public void setErrKey(String errKey) {
		this.errKey = errKey;
	}

	public String getErrMsg() {
		return errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}

}
